package com.paxcheckup.reporter.ui.screens

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoFixHigh
import androidx.compose.material.icons.filled.BatteryFull
import androidx.compose.material.icons.filled.CameraAlt
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.CreditCard
import androidx.compose.material.icons.filled.Error
import androidx.compose.material.icons.filled.HelpOutline
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Keyboard
import androidx.compose.material.icons.filled.NetworkWifi
import androidx.compose.material.icons.filled.Pending
import androidx.compose.material.icons.filled.PhotoCamera
import androidx.compose.material.icons.filled.Print
import androidx.compose.material.icons.filled.QrCodeScanner
import androidx.compose.material.icons.filled.ScreenShare
import androidx.compose.material.icons.filled.SkipNext
import androidx.compose.material.icons.filled.Summarize
import androidx.compose.material.icons.filled.VolumeUp
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import com.paxcheckup.reporter.data.TestCategory
import com.paxcheckup.reporter.data.TestStatus
import com.paxcheckup.reporter.ui.theme.FailRed
import com.paxcheckup.reporter.ui.theme.NotTestedGray
import com.paxcheckup.reporter.ui.theme.PassGreen
import com.paxcheckup.reporter.ui.theme.SkipYellow
import com.paxcheckup.reporter.viewmodel.TestViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun HomeScreen(navController: NavController, viewModel: TestViewModel) {
    val session by viewModel.session
    val isGeneratingPdf by viewModel.isGeneratingPdf
    val pdfGenerated by viewModel.pdfGenerated
    val context = LocalContext.current
    var techName by remember { mutableStateOf(session.technicianName) }
    var location by remember { mutableStateOf(session.location) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("PAX CheckUp Reporter", color = Color.White) },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primary
                )
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { navController.navigate(ScreenRoutes.REPORT) },
                containerColor = MaterialTheme.colorScheme.secondary
            ) {
                Icon(Icons.Default.Summarize, "Generate Report", tint = Color.White)
            }
        }
    ) { padding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            item {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("Device Info", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                        Spacer(modifier = Modifier.height(8.dp))
                        Text("Model: ${session.deviceModel}", style = MaterialTheme.typography.bodyMedium)
                        Text("Serial: ${session.serialNumber}", style = MaterialTheme.typography.bodyMedium)
                        Text("Android: ${android.os.Build.VERSION.RELEASE}", style = MaterialTheme.typography.bodyMedium)
                    }
                }
            }

            item {
                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    OutlinedTextField(
                        value = techName,
                        onValueChange = { techName = it; viewModel.updateTechnicianInfo(techName, location) },
                        label = { Text("Technician Name") },
                        modifier = Modifier.weight(1f)
                    )
                    OutlinedTextField(
                        value = location,
                        onValueChange = { location = it; viewModel.updateTechnicianInfo(techName, location) },
                        label = { Text("Location") },
                        modifier = Modifier.weight(1f)
                    )
                }
            }

            item {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("Overall Progress", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                        Spacer(modifier = Modifier.height(8.dp))
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceEvenly) {
                            SummaryBadge("Pass", session.passCount, PassGreen, Icons.Default.CheckCircle)
                            SummaryBadge("Fail", session.failCount, FailRed, Icons.Default.Error)
                            SummaryBadge("Skip", session.skipCount, SkipYellow, Icons.Default.SkipNext)
                            SummaryBadge("Pending", session.notTestedCount, NotTestedGray, Icons.Default.Pending)
                        }
                        Spacer(modifier = Modifier.height(8.dp))
                        Text("${session.passCount + session.failCount + session.skipCount} / ${session.totalCount} tests completed", style = MaterialTheme.typography.bodySmall)
                    }
                }
            }

            item {
                Text("Test Categories", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, modifier = Modifier.padding(vertical = 8.dp))
            }

            items(TestCategory.values()) { category ->
                val (pass, fail, total) = viewModel.getCategoryCounts(category)
                val status = viewModel.getCategoryStatus(category)
                CategoryCard(
                    category = category,
                    passCount = pass,
                    failCount = fail,
                    totalCount = total,
                    status = status,
                    onClick = {
                        navController.navigate("category/${category.name}")
                    }
                )
            }

            item {
                Spacer(modifier = Modifier.height(16.dp))
                OutlinedButton(
                    onClick = { navController.navigate(ScreenRoutes.TEST_LIST) },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(8.dp)
                ) {
                    Icon(Icons.Default.Summarize, contentDescription = null)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("View All Tests")
                }
            }

            if (isGeneratingPdf) {
                item {
                    Box(modifier = Modifier.fillMaxWidth().padding(16.dp), contentAlignment = Alignment.Center) {
                        CircularProgressIndicator()
                    }
                }
            }

            pdfGenerated?.let { path ->
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        colors = CardDefaults.cardColors(containerColor = PassGreen.copy(alpha = 0.1f)),
                        border = BorderStroke(1.dp, PassGreen)
                    ) {
                        Column(modifier = Modifier.padding(16.dp)) {
                            Text("PDF Generated Successfully!", color = PassGreen, fontWeight = FontWeight.Bold)
                            Text("Saved to: $path", style = MaterialTheme.typography.bodySmall)
                        }
                    }
                }
            }

            item { Spacer(modifier = Modifier.height(80.dp)) }
        }
    }
}

@Composable
fun SummaryBadge(label: String, count: Int, color: Color, icon: ImageVector) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Icon(icon, contentDescription = label, tint = color, modifier = Modifier.size(24.dp))
        Text("$count", color = color, fontWeight = FontWeight.Bold, fontSize = 18.sp)
        Text(label, color = color, fontSize = 10.sp)
    }
}

@Composable
fun CategoryCard(
    category: TestCategory,
    passCount: Int,
    failCount: Int,
    totalCount: Int,
    status: TestStatus,
    onClick: () -> Unit
) {
    val icon = when (category) {
        TestCategory.DISPLAY -> Icons.Default.ScreenShare
        TestCategory.KEYPAD -> Icons.Default.Keyboard
        TestCategory.CARD_READER -> Icons.Default.CreditCard
        TestCategory.PRINTER -> Icons.Default.Print
        TestCategory.SCANNER -> Icons.Default.QrCodeScanner
        TestCategory.CAMERA -> Icons.Default.PhotoCamera
        TestCategory.COMMUNICATION -> Icons.Default.NetworkWifi
        TestCategory.BATTERY -> Icons.Default.BatteryFull
        TestCategory.LED_SOUND -> Icons.Default.VolumeUp
        TestCategory.DEVICE_INFO -> Icons.Default.Info
        TestCategory.ONE_KEY_DETECT -> Icons.Default.AutoFixHigh
    }

    val statusColor = when (status) {
        TestStatus.PASS -> PassGreen
        TestStatus.FAIL -> FailRed
        TestStatus.SKIPPED -> SkipYellow
        TestStatus.PARTIAL -> SkipYellow
        else -> NotTestedGray
    }

    val statusIcon = when (status) {
        TestStatus.PASS -> Icons.Default.CheckCircle
        TestStatus.FAIL -> Icons.Default.Error
        TestStatus.SKIPPED -> Icons.Default.SkipNext
        TestStatus.PARTIAL -> Icons.Default.HelpOutline
        else -> Icons.Default.Pending
    }

    Card(
        onClick = onClick,
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        shape = RoundedCornerShape(12.dp),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Icon(icon, contentDescription = null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(40.dp))
            Spacer(modifier = Modifier.width(16.dp))
            Column(modifier = Modifier.weight(1f)) {
                Text(category.displayName, fontWeight = FontWeight.SemiBold, fontSize = 16.sp)
                Text("$passCount / $totalCount passed", style = MaterialTheme.typography.bodySmall, color = Color.Gray)
            }
            Icon(statusIcon, contentDescription = null, tint = statusColor, modifier = Modifier.size(28.dp))
        }
    }
}
