package com.paxcheckup.reporter.ui.screens

import android.content.Intent
import android.widget.Toast
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Error
import androidx.compose.material.icons.filled.FileDownload
import androidx.compose.material.icons.filled.Pending
import androidx.compose.material.icons.filled.Share
import androidx.compose.material.icons.filled.SkipNext
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import androidx.navigation.NavController
import com.paxcheckup.reporter.data.TestStatus
import com.paxcheckup.reporter.ui.theme.FailRed
import com.paxcheckup.reporter.ui.theme.NotTestedGray
import com.paxcheckup.reporter.ui.theme.PassGreen
import com.paxcheckup.reporter.ui.theme.SkipYellow
import com.paxcheckup.reporter.viewmodel.TestViewModel
import java.io.File
import java.text.SimpleDateFormat
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReportScreen(navController: NavController, viewModel: TestViewModel) {
    val session by viewModel.session
    val allTests by viewModel.testItems
    val isGeneratingPdf by viewModel.isGeneratingPdf
    val pdfGenerated by viewModel.pdfGenerated
    val context = LocalContext.current
    val scrollState = rememberScrollState()

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Generate Report", color = Color.White) },
                navigationIcon = {
                    IconButton(onClick = { navController.navigateUp() }) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back", tint = Color.White)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.primary)
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp)
                .verticalScroll(scrollState),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer),
                shape = RoundedCornerShape(12.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Report Preview", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("Device: ${session.deviceModel}", style = MaterialTheme.typography.bodyMedium)
                    Text("Technician: ${session.technicianName.ifBlank { "Not set" }}", style = MaterialTheme.typography.bodyMedium)
                    Text("Location: ${session.location.ifBlank { "Not set" }}", style = MaterialTheme.typography.bodyMedium)
                    val dateStr = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault()).format(session.startTime)
                    Text("Date: $dateStr", style = MaterialTheme.typography.bodyMedium)
                }
            }

            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceEvenly) {
                CountBadge("Pass", session.passCount, PassGreen, Icons.Default.CheckCircle)
                CountBadge("Fail", session.failCount, FailRed, Icons.Default.Error)
                CountBadge("Skip", session.skipCount, SkipYellow, Icons.Default.SkipNext)
                CountBadge("Pending", session.notTestedCount, NotTestedGray, Icons.Default.Pending)
            }

            val passPercent = if (session.totalCount > 0) (session.passCount * 100 / session.totalCount) else 0
            Text("Pass Rate: $passPercent% (${session.passCount} / ${session.totalCount})", fontWeight = FontWeight.SemiBold, fontSize = 16.sp)

            val overallStatus = session.overallStatus
            val overallColor = when (overallStatus) {
                TestStatus.PASS -> PassGreen
                TestStatus.FAIL -> FailRed
                TestStatus.SKIPPED -> SkipYellow
                TestStatus.PARTIAL -> SkipYellow
                else -> NotTestedGray
            }
            Text(
                "Overall Status: ${overallStatus.name}",
                fontWeight = FontWeight.Bold,
                fontSize = 18.sp,
                color = overallColor
            )

            if (session.failCount > 0) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = FailRed.copy(alpha = 0.1f)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("Failed Tests (${session.failCount})", color = FailRed, fontWeight = FontWeight.Bold)
                        allTests.filter { it.status == TestStatus.FAIL }.forEach { test ->
                            Text("- ${test.name} (${test.category.displayName})", color = FailRed, fontSize = 13.sp)
                        }
                    }
                }
            }

            if (session.notTestedCount > 0) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = NotTestedGray.copy(alpha = 0.1f)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("Not Yet Tested (${session.notTestedCount})", color = NotTestedGray, fontWeight = FontWeight.Bold)
                        Text("Some tests have not been performed. You can still generate the report, but it will be marked as incomplete.", fontSize = 13.sp, color = NotTestedGray)
                    }
                }
            }

            Spacer(modifier = Modifier.height(8.dp))

            Button(
                onClick = {
                    viewModel.resetPdfState()
                    viewModel.generatePdf(context)
                },
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(10.dp),
                enabled = !isGeneratingPdf
            ) {
                if (isGeneratingPdf) {
                    CircularProgressIndicator(modifier = Modifier.size(20.dp), color = Color.White, strokeWidth = 2.dp)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generating PDF...")
                } else {
                    Icon(Icons.Default.FileDownload, contentDescription = null)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generate PDF Report")
                }
            }

            pdfGenerated?.let { path ->
                Spacer(modifier = Modifier.height(8.dp))
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = PassGreen.copy(alpha = 0.15f)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("PDF Generated Successfully!", color = PassGreen, fontWeight = FontWeight.Bold, fontSize = 16.sp)
                        Text("File: ${File(path).name}", style = MaterialTheme.typography.bodySmall)
                        Spacer(modifier = Modifier.height(8.dp))
                        OutlinedButton(
                            onClick = {
                                val file = File(path)
                                if (file.exists()) {
                                    val uri = FileProvider.getUriForFile(
                                        context,
                                        "${context.packageName}.provider",
                                        file
                                    )
                                    val shareIntent = Intent(Intent.ACTION_SEND).apply {
                                        type = "application/pdf"
                                        putExtra(Intent.EXTRA_STREAM, uri)
                                        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                                    }
                                    context.startActivity(Intent.createChooser(shareIntent, "Share Report"))
                                } else {
                                    Toast.makeText(context, "File not found", Toast.LENGTH_SHORT).show()
                                }
                            },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Icon(Icons.Default.Share, contentDescription = null)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Share PDF")
                        }
                    }
                }
            }

            OutlinedButton(
                onClick = { viewModel.resetAllTests() },
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(10.dp)
            ) {
                Text("Reset All Tests")
            }

            Spacer(modifier = Modifier.height(80.dp))
        }
    }
}

@Composable
fun CountBadge(label: String, count: Int, color: Color, icon: androidx.compose.ui.graphics.vector.ImageVector) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Icon(icon, contentDescription = label, tint = color, modifier = Modifier.size(32.dp))
        Text("$count", color = color, fontWeight = FontWeight.Bold, fontSize = 20.sp)
        Text(label, color = color, fontSize = 12.sp)
    }
}
